### ISSUE TITLE
Implement multi language

### ISSUE THREAD

**Issue by danilohbp** [AddressForAll/site-v2#1]
## Ideas

Consider using json's or multilanguage routes to direct the user to the page with content in the language of their choice

**Comment by elpbatista** [comment]
There is also another way to do it, better for SEO, using `<spam lang="es">texto en Español</spam><spam lang="en">English text<spam>` and show/hide the current language text adding a CSS class via JavaScript

**Comment by danilohbp** [comment]
OK! So when the user chooses a language we pass this as props in the "lang" attribute and the textual part will be injected according to that attribute and another factor that precisely defines that text in that tag

**Comment by elpbatista** [comment]
The text will be displayed instead of being dynamically injected because it will already be embedded but hidden.

**Comment by danilohbp** [comment]
Good!

**Comment by ppKrauss** [comment]
Vou especificar melhor em [docs/generalSpec](https://github.com/AddressForAll/site-v2/blob/main/docs/en/generalSpec.md), mas por hora dois resultados importantes no detalhamento dos requisitos:

1. apenas o menu de navegação e interfaces animadas (ex. mapas dinâmicos e seletores dinâmicos) podem ter o seu "template de língua" resolvido em client-side.
2. As diferentes línguas do conteúdo institucional serão gerenciadas como páginas distintas e "montadas" em server-site

**Comment by ppKrauss** [comment]
resolvido com JSON, **pendente com HTML ou Markdown**
