### ISSUE TITLE
acrescentar manual completo de instalação do Node no Ubuntu LTS

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/site-v2#20]
Na AddressForAll o Ubuntu LTS é o "sistema operacional oficial", atualmente usuários de ambos,  Ubuntu 20.04 LTS  e Ubuntu 22.04 LTS (Jellyfish).  Aparentemente é **impossível** instalar uma versão moderna de nodejs com `apt install nodejs`... Precisa ser via PPA, mas mesmo com PPA temos limitações, talvez não mais que *NodeJS version 16*.

No Ubuntu via `apt` o melhor que se consegue é **Node.js v12**.

Uma vez estabelecida a "versão oficial", compatibilizar o software do site-v2 para isso.

Também documentar a instalação na Wiki.

Referencia a atualizar: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04

**Comment by crebollobr** [comment]
Usamos o daemon pm2 com o usuário pm2
Esse daemon controla os sites que serão inicializado no boot e ele mantem os sites funcionando 
Referencia
https://github.com/AddressForAll/suporte/blob/master/docs/pt/nodejs.md

**Comment by elpbatista** [comment]
¿Por qué usar PM2 para publicar sitios estáticos cuando podría resolverlo de manera más sencilla usando Nginx? Hasta ahora en ningún caso se están publicando React apps, todos los sitios son pre-renderizados así que basta apuntar al build/ en el sistema de archivo ya sea con un enlace virtual desde la carpeta de publicación, un directorio virtual o cualquier variante de publicación que puede ser proxy inverso si es que tienes servidores en cascada

**Comment by ppKrauss** [comment]
> Pessoal a versão atual do site teste2.addressforall.org é estática, não usa o node.js

O que se pede nessa issue é a liberdade de reinstalar e **testar o software NodeJS na sua máquina Ubuntu**.

REABRINDO: [suporte/docs/pt/nodejs.md](https://github.com/AddressForAll/suporte/blob/master/docs/pt/nodejs.md) não resolve e precisa remover o PM2, a decisão confirmada aqui é que não usaremos PM2.

**Comment by ppKrauss** [comment]
Solução parcial, https://github.com/AddressForAll/suporte/blob/master/docs/pt/nodejs.md com rascunho.
Se resolver bugs da issue #22 passar a limpo, senão revisar questão da versão.

**Comment by ppKrauss** [comment]
suporte/docs concluído com 

* definição oficial das versões a serem adotadas, [suporte/docs/pt/infra.md](https://github.com/AddressForAll/suporte/blob/master/docs/pt/infra.md#ambientes-e-ferramentas-de-uso-geral).
* Página *suporte/docs* de instalação NodeJS revisada, https://github.com/AddressForAll/suporte/blob/master/docs/pt/nodejs.md
