### ISSUE TITLE
Menu funcionando com celular

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/site-v2#25]
Usar tecnologia do site atual, https://addressforall.org

## Requisito da opção de linguas

As linguas são mais um item de menu com sub-menu, não criar nada separado... Depois com CSS renderizamos cores e destaques.

## Requisito geral

O menu não pode entrar "explodido", precisa entrar com submenus fechados. Ao clicar precisa  despachar para a seção clicada, não pode continuar no mesmo lugar. Abaixo o   comportamento reativo ao tamanho de tela.

Tela larga:
![image](https://user-images.githubusercontent.com/1651447/178727263-d06337e9-8b27-44a6-a10e-d5d7975c31c9.png)

tela media-larga
![image](https://user-images.githubusercontent.com/1651447/178727448-f6ace3d3-225d-4e0c-b7d0-3d4245eb232d.png)

Limiar de desktop
![image](https://user-images.githubusercontent.com/1651447/178727574-3dada8c6-5f99-4247-937c-3fcedd1edfea.png)

Modo celular
![image](https://user-images.githubusercontent.com/1651447/178727708-4937e2c2-e282-4754-9246-62b6f1f9c5c7.png)

Menu aberto no celular
![image](https://user-images.githubusercontent.com/1651447/178727837-bbd3f369-a283-44e2-8885-6805abf632df.png)

**Comment by elpbatista** [comment]
Ya está e menú hamburguesa. Mira las capturas de pantalla a continuación:

<img width="360" alt="Screen Shot 2022-07-13 at 10 51 38 AM" src="https://user-images.githubusercontent.com/5332055/178765052-2f150159-1c0a-4dd9-b462-9e2be4b665ca.png">

<img width="360" alt="Screen Shot 2022-07-13 at 10 51 49 AM" src="https://user-images.githubusercontent.com/5332055/178765192-c19d7c9a-3379-4e91-8dad-35ef4bbf6506.png">
