### ISSUE TITLE
Implement Components

### ISSUE THREAD

**Issue by danilohbp** [AddressForAll/site-v2#3]
Develop the necessary components to be used as templates to contain the dynamic and static content of the page.

**Comment by danilohbp** [comment]
Implementing container components: **Main, Section, Row, Container** and componentizing sections in **.js** files, to separate for example: **About.js, Advertisment.js, SearchAddr.js** and then join all these component sections in a single page, ie , set up a SPA (Single Page Application), it was agreed with @Batista to develop the site in this format.

**Comment by ppKrauss** [comment]
ok
