### ISSUE TITLE
Falha no site

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/site-v2#53]
Banch issues/24

Nossa versão de software é
node -v v18.15.0
npm -v 9.4.0

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Sequencia de comandos
git clone -b issues/24 https://github.com/AddressForAll/site-v2.git
cd site-v2/
npm install
npm run dev

no site /about 

![image](https://user-images.githubusercontent.com/22559999/231601086-fcaf108b-3ced-4fd1-ac17-9bc8c4994b8e.png)

![image](https://user-images.githubusercontent.com/22559999/231601222-b6cf24e7-fd06-4b42-9447-635f0f4fd408.png)

![image](https://user-images.githubusercontent.com/22559999/231601277-6ddc007f-4daf-4128-a169-9f52e35fe844.png)

**Comment by ppKrauss** [comment]
@ArrthurGeronimo o seu PullRequest será aprovado somente depois de resolvida essa issue sobre versão do Node. 

Ver também https://github.com/AddressForAll/suporte/blob/master/docs/pt/infra.md

**Comment by ArrthurGeronimo** [comment]
O erro de hidratação é meio que comum no Nextjs, ocorre quando a interface inicial não condiz com a interface criada no servidor. O problema desse erro é que ele pode ser gerado por diversos motivos, mas os mais comuns estão relacionados com tags HTML indevidas.

Olhando o projeto identifiquei onde estão os problemas. Atualmente estão na página `home` e `about`. 
Foi criado um componente chamado `Link` onde ele possui uma tag de link dentro `<a></a>`, e nessas páginas esse componente é utilizado passando outra tag `<a>` como _children_, ou seja, uma tag `<a>` dentro de outra tag `<a>`, ocasionando assim uma inconsistência no HTML e gerando o erro de hidratação no Nextjs.

Exemplo de uma inconsistência do site abaixo:
![image](https://user-images.githubusercontent.com/28739009/233807884-2f3eb9ac-959c-4c77-a350-bc5510df7b85.png)

A solução é simples, basta substituir a tag filha por outro elemento. 

Por sugestão do @ppKrauss , irei substituir as tags inconsistentes por `span`.

Irei subir um commit com essa correção 👍
