### ISSUE TITLE
Falha no make build

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/site-v2#54]
git clone https://github.com/AddressForAll/site-v2.git
cd site-v2
make build

quando visita o site não aparece nada e ocorre erro de javascript

![image](https://user-images.githubusercontent.com/22559999/233691110-e36c41e7-7f6e-4fca-b939-c680efa31baf.png)

**Comment by ppKrauss** [comment]
@ArrthurGeronimo por favor comparar com versão antiga, é **algo que você  fez no NEXT destruindo totalmente a geração "build HTML puro"**. Antes gravava tudo na pasta `/out`.

**Comment by ArrthurGeronimo** [comment]
Olá!
Então, realizei alguns testes aqui e tenho algumas considerações.

Sobre a questão de configurações no Next, eu não alterei nada, não instalei nenhuma dependência e nem alterei nenhum arquivo. Olhei os commits do projeto e as minhas alterações com status `merged` estão somente no componente do funil e são basicamente css, o que não ocasionaria esse erro.

Sobre o comando `make build`, não consegui simular aqui, não sei se é algo exclusivo do Linux, mas de qualquer forma a build do próprio Next está funcionando (`npm run build` / `yarn build`), inclusive criando a pasta `/out`.

De qualquer forma me coloco a disposição para ajudar, mas antes gostaria de entender como funciona esse comando e a hospedagem de vocês para saber onde procurar a solução do problema

**Comment by ppKrauss** [comment]
> Sobre o comando `make build`, não consegui simular aqui, não sei se é algo exclusivo do Linux, mas de qualquer forma a build do próprio Next está funcionando (`npm run build` / `yarn build`), inclusive criando a pasta `/out`.

Acho que expliquei mal o problema: gera sim o build no `/out` ,  mas não é o que gerava antes, está gerando só algumas linhas de HTML contendo chamada javascript.
Não queremos javascript (site expresso dinamicamente no DOM),
 olha o site AddressForAll.org vigente, não é javascript, é um site de puro **HTML estático**.

## Como precisa ser e sempre foi

```html
<!DOCTYPE html><html>
<head>
<meta name="viewport" content="width=device-width"/><meta charSet="utf-8"/>
<title>A4A - AddressForAll</title>
...
<script>...</script></head>
<body><div id="__next">
<svg xmlns="http://www.w3.org/2000/svg" class="hidden">
...</svg>
<header><div class="brand">...</div>...</header>
...
</body></html>
```

## Como ficou depois da alteração com bug
ISSO É BUG, NÃO TEM NADA DE HTML ESTÁTICO, SÓ JAVASCRIPT.
```html
<!DOCTYPE html><html>
<head><meta name="viewport" content="width=device-width"/><meta charSet="utf-8"/>
<title>A4A - AddressForAll</title>...
<script>...</script>
</head>
<body><div id="__next"></div>
<script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/","query":{},"buildId":"d1rOs6XzTMWMnz
dpbTHSK","nextExport":true,"autoExport":true,"isFallback":false,"scriptLoader":[]}</script>
</body></html>
```

**Comment by 0e1** [comment]
Usar  `make build-only` no lugar de  `make build`.

`make build` executa o target `rm_rehydration`. É a execução do `rm_rehydration` que causa o problema.

**Comment by crebollobr** [comment]
Vou fechar a issue
