### ISSUE TITLE
Atualizar download com tudo, total e completo

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/site-v2#56]
Download desatualizado ou incompleto é bug. A página http://addressforall.org/en/downloads/
precisa conter todos os pacotes, cada um com todos os seus downloads, incluindo SHP de cada layer filtrado.

**Comment by ppKrauss** [comment]
Fechando, parece tudo ok. @0e1 disponibilizou em http://teste2.addressforall.org/en/downloads/

@IgorEliezer conferir, se tudo ok, avisa Claiton para passar para produção

**Comment by 0e1** [comment]
ver também https://wiki.addressforall.org/doc/dg:Listagem_dos_downloads_por_jurisdi%C3%A7%C3%A3o

**Comment by ppKrauss** [comment]
Detalhe final:  a cada Cidade e a cada pacote fazer um span ou acrescentar no `<LI>` um `id`.

Por exemplo  `<li><strong>BR-AC-RioBranco</strong><ul>`
vira `<li id="BR-AC-RioBranco"><strong>BR-AC-RioBranco</strong><ul>`
para poder referenciar em URL, http://addressforall.org/en/downloads#BR-AC-RioBranco

Idem código de pacote, 
`<li><a href="https://git.digital-guard.org/preserv-BR/blob/main/data/AC/RioBranco/_pk0042.01">_pk0042</a>`
vira
`<li id="_pk0042"><a href="https://git.digital-guard.org/preserv-BR/blob/main/data/AC/RioBranco/_pk0042.01">_pk0042</a>`.

**Comment by IgorEliezer** [comment]
> ver também https://wiki.addressforall.org/doc/dg:Listagem_dos_downloads_por_jurisdi%C3%A7%C3%A3o

Movi para um template dedicado, assim não precisa ficar navegando pelo código da página: https://wiki.addressforall.org/doc/Predefini%C3%A7%C3%A3o:Dg-download-list

Qualquer lugar da wiki que tiver a tag {{Dg-download-list}}, vai carregar a lista. ([exemplo](https://wiki.addressforall.org/doc/dg:Listagem_dos_downloads_por_jurisdi%C3%A7%C3%A3o))

**Comment by IgorEliezer** [comment]
> @IgorEliezer conferir, se tudo ok, avisa Claiton para passar para produção

@0e1: Testei 12 links. Baixaram. Todos abriram no QGIS.

![image](https://github.com/AddressForAll/site-v2/assets/4673289/77c43cce-ebbc-45a4-b59c-e2024f8bda78)

Só BR-SP-SaoBernardoCampo tem um **** no link e não consigo baixar.

![image](https://github.com/AddressForAll/site-v2/assets/4673289/5838fb41-07a5-40d8-9872-3b1901d7c1d8)

**Comment by 0e1** [comment]
> Detalhe final: a cada Cidade e a cada pacote fazer um span ou acrescentar no `<LI>` um `id`.
> 
> Por exemplo `<li>\<strong\>BR-AC-RioBranco\</strong\><ul>` vira `<li id="BR-AC-RioBranco">\<strong\>BR-AC-RioBranco\</strong\><ul>` para poder referenciar em URL, http://addressforall.org/en/downloads#BR-AC-RioBranco
> 
> Idem código de pacote, `<li><a href="https://git.digital-guard.org/preserv-BR/blob/main/data/AC/RioBranco/_pk0042.01">_pk0042</a>` vira `<li id="_pk0042"><a href="https://git.digital-guard.org/preserv-BR/blob/main/data/AC/RioBranco/_pk0042.01">_pk0042</a>`.

Lembrar que o código html é gerado a partir de arquivo markdown. Então optei por usar `span`.
