### ISSUE TITLE
Colocar licenças e seus links na página de download

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/site-v2#58]
Conforme combinado na reunião técnica de 05/09/2023, precisamos colocar na página de Downloads (http://addressforall.org/en/downloads/), para cada pacote, ao lado do link _pk, a licença e o seu link corresponde.

A razão é para que os usuários e parceiros possam ver não só quais pacotes temos, mas também a licença dos mesmos.

**Comment by 0e1** [comment]
Fiz o necessário para incluir.

Verificar em:

http://addressforall.org/downloads/
https://wiki.addressforall.org/doc/Predefinição:Dg-download-list

***

Notar que nos pacotes sem licença o problema está no preenchimento errado de _donatedPack.csv_.
