### ISSUE TITLE
Melhorias para tornar a página Downloads mais user-friendly

### ISSUE THREAD

**Issue by IgorEliezer** [AddressForAll/site-v2#61]
Acabei de ter uma conversa com @ppKrauss sobre a página [Downloads ](https://addressforall.org/pt/downloads/) e fizemos testes como se fossemos um visitante novo que quer ver e baixar os dados.

Segue uma lista de sugestões de melhorias que facilitariam a navegação e informam o usuário.

- [x] 1. Adicionar uma barra horizontal de links para os países antes da template.
- [x] 2. Adicionar os termos "Package" e "license".

Detalho:
1. É uma barra de links com um link para cada país. Clique em um link para saltar direto para o país.

![image](https://github.com/AddressForAll/site-v2/assets/4673289/12e8d17d-0cef-4c34-a838-934061621186)

2. O usuário não sabe o que são estes _pks e talvez não esteja acostumado com as terminologias das licenças. Então coloquemos o que são. Deve ficar assim:

**BR-AC-RioBranco**
___ Prefeitura Municipal de Rio Branco
_______Package pk0042 (licence: Implied BR-generic-1.0) [unprecedented]

**Comment by 0e1** [comment]
@IgorEliezer 

Realizei as melhorias.

Ver em https://addressforall.org/downloads/

**Comment by 0e1** [comment]
Se tiver outras melhorias, relate.
